[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "forge-std/=lib/forge-std/src/",
    "Solidity-RLP/=lib/Solidity-RLP/contracts/",
    "aa/=lib/aa-v0.6/contracts/",
    "solady/=lib/solady/src/",
]

[fmt]
sort_imports = true
wrap_comments = true
